import { Roboto } from "next/font/google";
import "../styles/global.css";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
});

export const metadata = {
  title: 'Webapp by Next.js',
  description: 'Generated by Next.js',
  icons: {
    icon: "https://img.notionusercontent.com/s3/prod-files-secure%2F4904af9e-6649-4d24-81b7-6a8fad9a201e%2F770caa26-6d89-4f0b-9c16-49e22f1a4731%2Fnextjs.ico/size/?exp=1730795476&sig=5F_aRRcuAGH9kYUO2K0h5fsh788luBDEoX4LYCKRYHg",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
